title = "FreeJaus - Forge"
baseurl = "http://freejaus.github.io"

[params]
  description = "This is the description"
  author = "This is the author"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.notebook]]
  name = "Get full content"
  pre = "download"
  url = ""
  identifier = "nb-down"
  weight = -200
